import NavBar from '../Components/NavBar';

function About() {
    return (
    <div className="about-page">
    <NavBar />
    <h1>About Page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Tristique risus nec feugiat in fermentum posuere urna. Sed egestas egestas fringilla phasellus. Pharetra pharetra massa massa ultricies mi quis hendrerit. Arcu non sodales neque sodales. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Sed arcu non odio euismod lacinia at quis risus. Commodo viverra maecenas accumsan lacus vel facilisis. Placerat duis ultricies lacus sed. Diam sollicitudin tempor id eu. Dictum at tempor commodo ullamcorper a lacus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Id diam vel quam elementum pulvinar etiam non quam lacus. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Commodo quis imperdiet massa tincidunt nunc pulvinar. Faucibus purus in massa tempor nec feugiat nisl pretium. Odio morbi quis commodo odio aenean sed. Scelerisque felis imperdiet proin fermentum leo.

Hendrerit dolor magna eget est lorem ipsum dolor sit amet. Mauris sit amet massa vitae tortor. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Nisl pretium fusce id velit ut tortor pretium viverra. Proin sagittis nisl rhoncus mattis. Quis vel eros donec ac. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Quam vulputate dignissim suspendisse in est. Eu feugiat pretium nibh ipsum consequat. Cursus risus at ultrices mi tempus. Congue mauris rhoncus aenean vel. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Ut porttitor leo a diam sollicitudin tempor id. Gravida rutrum quisque non tellus orci. Eget aliquet nibh praesent tristique magna sit amet.

Convallis convallis tellus id interdum velit laoreet id donec ultrices. Eget lorem dolor sed viverra ipsum nunc. Accumsan sit amet nulla facilisi morbi tempus. Mi proin sed libero enim sed. Sit amet justo donec enim diam vulputate ut pharetra. Urna id volutpat lacus laoreet non curabitur. Rutrum tellus pellentesque eu tincidunt tortor. Tempus urna et pharetra pharetra massa. Ornare suspendisse sed nisi lacus sed viverra tellus. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Sodales neque sodales ut etiam sit. Nisi vitae suscipit tellus mauris. Convallis a cras semper auctor. Sem integer vitae justo eget magna fermentum. Libero justo laoreet sit amet cursus sit amet dictum. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Adipiscing elit pellentesque habitant morbi tristique senectus et netus et.

Et netus et malesuada fames. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Fermentum iaculis eu non diam phasellus vestibulum lorem. Amet nisl suscipit adipiscing bibendum est ultricies. Vestibulum rhoncus est pellentesque elit ullamcorper. Quam viverra orci sagittis eu. Id consectetur purus ut faucibus pulvinar elementum. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Ornare massa eget egestas purus viverra accumsan in. In hac habitasse platea dictumst vestibulum rhoncus est. Donec ultrices tincidunt arcu non sodales neque. Turpis tincidunt id aliquet risus feugiat in ante metus dictum.

Ut tristique et egestas quis ipsum. Vitae tempus quam pellentesque nec nam. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Cras sed felis eget velit aliquet sagittis. Quis ipsum suspendisse ultrices gravida dictum. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Vitae ultricies leo integer malesuada nunc. Morbi tincidunt ornare massa eget egestas purus viverra. Platea dictumst quisque sagittis purus. Leo in vitae turpis massa sed elementum tempus egestas. Morbi tristique senectus et netus. In iaculis nunc sed augue lacus. Tincidunt eget nullam non nisi est. Turpis nunc eget lorem dolor sed viverra ipsum. Ipsum dolor sit amet consectetur adipiscing elit duis. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing.</p>
    </div>
    )
}
export default About;